### ISSUE TITLE
Incompatibility of 5.2.0 with Python 3.7

### ISSUE THREAD

**Issue by zopyx** [collective/i18ndude#68]
```
ajung@dev ~/src/xmldirector.connector (master) $ bin/i18ndude 
Traceback (most recent call last):
  File "bin/i18ndude", line 11, in <module>
    sys.exit(main())
  File "/home/ajung/src/xmldirector.connector/lib/python3.7/site-packages/i18ndude/script.py", line 735, in main
    errors = arguments.func(arguments)
AttributeError: 'Namespace' object has no attribute 'func'

```

**Comment by mauritsvanrees** [comment]
Hard to fix until 'someone' fixes the test buildout on Python 3.7. See issue #66 and PR #67.
I wonder if it works when you call the script with a command, for example `bin/i18ndude rebuild-pot --help`.

**Comment by mauritsvanrees** [comment]
I actually see the same problem in Python 3.6.
Hopefully fixed in PR #70.

**Comment by mauritsvanrees** [comment]
And something like `bin/i18ndude rebuild-pot --help` already works with 5.2.0, it is only that plain `bin/i18ndude` without arguments fails.

**Comment by mauritsvanrees** [comment]
Fixed in 5.3.0.
